data:
  aux: celeba-aux
  name: celeba
  target: celeba-target
evaluation_cls:
  class: FinetunednsightFaceClassifier
  name: Finetuned
  path: pretrained/eval_clf/celeba/ckpt_e14.pt
target_cls:
  name: ResNet34
  path: pretrained/classifiers/neurips2021-celeba-cls/best_ckpt.pt